apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-demo
  namespace: prod-environment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-demo
    spec:
      containers:
      - env:
        - name: INGEST_API
          value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}
        image: quay.io/humancellatlas/ingest-demo:v0.4.0.rc
        imagePullPolicy: Always
        name: ingest-demo
        ports:
        - containerPort: 5000
