apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-state-tracking
  namespace: prod-environment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-state-tracking
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: ${RABBIT_SERVICE_SERVICE_HOST}
        - name: RABBIT_PORT
          value: ${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        - name: INGEST_API_ROOT
          value: http://api.ingest.data.humancellatlas.org
        - name: UPDATER_PERIOD_SECONDS
          value: "1"
        image: quay.io/humancellatlas/ingest-state-tracking:v0.5.0
        imagePullPolicy: Always
        name: ingest-state-tracking
