apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-core
  namespace: prod-environment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-core
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb://${MONGO_SERVICE_SERVICE_HOST}:${MONGO_SERVICE_SERVICE_PORT}/admin
        - name: RABBIT_HOST
          value: ${RABBIT_SERVICE_SERVICE_HOST}
        - name: RABBIT_PORT
          value: ${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        image: quay.io/humancellatlas/ingest-core:v0.4.0.rc
        imagePullPolicy: Always
        name: ingest-core
        ports:
        - containerPort: 8080
