---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingest-validator
  namespace: staging-environment
  labels:
    role: ingestion
spec:
  replicas: 50
  strategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: ingest-validator
    spec:
      containers:
         - name: ingest-validator
           image: quay.io/humancellatlas/ingest-validator:v0.0.4.rc
           env:
             - name: INGEST_API
               value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
             - name: RABBIT_URL
               value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
             - name: RABBITMQ_ACCESSION_QUEUE
               value: ingest.metadata.accession.queue
             - name: RABBITMQ_VALIDATION_QUEUE
               value: ingest.metadata.validation.queue
