ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.dev.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.dev.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.dev.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: ui.ingest.dev.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:861229788715:certificate/bc640e02-86e7-4e1a-a9cc-034fbf4bd378

