ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.integration.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.integration.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.integration.data.humancellatlas.org
      - service: ingest-ui-service
        hostname: ui.ingest.integration.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:861229788715:certificate/e91f5627-09ed-43d6-8d2d-ee34ffab06ec
