ingress:
  enabled: "false"      

# for subchart stable/nginx-ingress

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      targetPorts:
          https: http
  rbac:
    create: "true"
