apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Values.namespace }}"
  annotations: {}
  labels:
    role: ingestion
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "mongo.chart" . }}
  name: mongo-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  sessionAffinity: None
  type: ClusterIP
