apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-core
  namespace: {{ .Values.environment }}-environment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-core
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb://${MONGO_SERVICE_SERVICE_HOST}:${MONGO_SERVICE_SERVICE_PORT}/admin
        - name: RABBIT_HOST
          value: ${RABBIT_SERVICE_SERVICE_HOST}
        - name: RABBIT_PORT
          value: ${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        - name: SCHEMA_BASE_URI
          value: https://{{ .Values.schema }}/
        - name: STATE_TRACKER_HOST
          value: $(INGEST_STATE_TRACKING_SERVICE_SERVICE_HOST)
        - name: STATE_TRACKER_PORT
          value: $(INGEST_STATE_TRACKING_SERVICE_SERVICE_PORT)
        - name: GCP_PROJECT_WHITELIST
          value: {{ .Values.gcpProjectWhitelist }}
        - name: SVC_AUTH_AUDIENCE
          value: {{ .Values.svcAuthAudience }}
        - name: USR_AUTH_AUDIENCE
          value: {{ .Values.usrAuthAudience }}
        - name: AUTH_ISSUER
          value: https://humancellatlas.auth0.com/
        image: quay.io/humancellatlas/ingest-core:{{ .Values.image }}
        imagePullPolicy: Always
        name: ingest-core
        ports:
        - containerPort: 8080
