apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: mongo
  namespace: integration-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-service
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:3.4.3
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
