apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-ontology
  namespace: {{ .Values.environment }}-environment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-ontology
    spec:
      containers:
      - image: quay.io/humancellatlas/ingest-exporter:{{ .Values.image }}
        imagePullPolicy: Always
        name: ontology
        ports:
        - containerPort: 8080
