#!/usr/bin/env bash
set -a

# Set this to TRUE if this environment uses branch tags and you want to force refresh helm deployments to kubernetes. 
# Set to FALSE if you are using tags.
FORCE_REFRESH_PODS=TRUE

# Versions of applications deployed. Either a branch or a tag that corresponds with an image in quay is accepted.
INGEST_ACCESSIONER_VERSION=master
INGEST_BROKER_VERSION=master
INGEST_CORE_VERSION=master
INGEST_EXPORTER_VERSION=master
INGEST_ONTOLOGY_VERSION=master
INGEST_STAGING_MANAGER_VERSION=master
INGEST_STATE_TRACKING_VERSION=master
INGEST_VALIDATOR_VERSION=master

# Variables that are different for each environment but should not change
AWS_PROFILE=hca
DEPLOYMENT_STAGE=dev
TF_VAR_vpc_cidr_block=10.20.0.0/16
TF_VAR_subnet_cidr_block_one=10.20.1.0/24
TF_VAR_subnet_cidr_block_two=10.20.2.0/24

# Static variables between environments. These should never change
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
KUBECONFIG=$PROJECT_ROOT/config/cluster-secrets/kubeconfig_${DEPLOYMENT_STAGE}
TILLER_NAMESPACE=kube-system
TF_VAR_terraform_key=ingest/eks-${DEPLOYMENT_STAGE}.tfstate
TF_VAR_aws_profile=${AWS_PROFILE}
TF_VAR_deployment_stage=${DEPLOYMENT_STAGE}
TF_VAR_account_id=$(aws sts get-caller-identity --profile ${AWS_PROFILE} | jq -r .Account)
TF_VAR_aws_region=us-east-1
TF_VAR_terraform_bucket=org-humancellatlas-${TF_VAR_account_id}-terraform

set +a
