#!/usr/bin/env bash
set -a

# Variables that change with each environment
AWS_PROFILE=hca
DEPLOYMENT_STAGE=integration
TF_VAR_vpc_cidr_block=10.30.0.0/16
TF_VAR_subnet_cidr_block_one=10.30.1.0/24
TF_VAR_subnet_cidr_block_two=10.30.2.0/24

# Static variables between environments
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"
KUBECONFIG=$PROJECT_ROOT/config/cluster-secrets/kubeconfig_${DEPLOYMENT_STAGE}
TILLER_NAMESPACE=${DEPLOYMENT_STAGE}-environment
TF_VAR_terraform_key=ingest/eks-${DEPLOYMENT_STAGE}.tfstate
TF_VAR_aws_profile=${AWS_PROFILE}
TF_VAR_deployment_stage=${DEPLOYMENT_STAGE}
TF_VAR_account_id=$(aws sts get-caller-identity --profile ${AWS_PROFILE} | jq -r .Account)
TF_VAR_aws_region=us-east-1
TF_VAR_terraform_bucket=org-humancellatlas-${TF_VAR_account_id}-terraform

set +a
