apiVersion: v1
data:
  aap-api-password: PHJlZGFjdGVkPg==
  staging-api-key: PHJlZGFjdGVkPg==
kind: Secret
metadata:
  annotations: {}
  name: api-keys
  namespace: {{ .Values.environment }}-environment
type: Opaque
