apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-exporter
  namespace: integration-environment
spec:
  replicas: 15
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ingest-exporter
    spec:
      containers:
      - env:
        - name: INGEST_API
          value: http://api.ingest.integration.data.humancellatlas.org:80
        - name: RABBIT_URL
          value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        - name: DSS_API
          value: https://dss.integration.data.humancellatlas.org
        - name: STAGING_API
          value: https://upload.integration.data.humancellatlas.org
        - name: INGEST_API_KEY
          valueFrom:
            secretKeyRef:
              key: staging-api-key
              name: api-keys
        image: quay.io/humancellatlas/ingest-exporter:integration
        imagePullPolicy: Always
        name: ingest-exporter
