ingress:
  ingest:
    defaultPath: /
    defaultServicePort: 80
    hosts:
      - service: ingest-core-service
        hostname: api.ingest.data.humancellatlas.org
      - service: ingest-broker-service
        hostname: ingest.data.humancellatlas.org
      - service: ontology-service
        hostname: ontology.data.humancellatlas.org

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:109067257620:certificate/1abf8978-a1c1-4b6c-9ee2-1ccc3f42f1dc

