apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations: {}
  labels:
    role: ingestion
  name: ingest-validator
  namespace: dev-environment
spec:
  replicas: 15
  template:
    metadata:
      labels:
        app: ingest-validator
    spec:
      dnsPolicy: Default
      containers:
      - env:
        - name: INGEST_API
          value: http://${INGEST_CORE_SERVICE_SERVICE_HOST}:${INGEST_CORE_SERVICE_SERVICE_PORT}
        - name: RABBIT_URL
          value: amqp://${RABBIT_SERVICE_SERVICE_HOST}:${RABBIT_SERVICE_SERVICE_PORT_SERVICE}
        - name: UPLOAD_API_URL
          value: https://upload.dev.data.humancellatlas.org
        - name: RABBITMQ_ACCESSION_QUEUE
          value: ingest.metadata.accession.queue
        - name: RABBITMQ_VALIDATION_QUEUE
          value: ingest.metadata.validation.queue
        - name: JSON_SCHEMA_VALIDATION
          value: ACTIVE
        - name: OLS_VALIDATION
          value: INACTIVE
        - name: FILE_VALIDATION
          value: ACTIVE
        - name: ONTOLOGY_SCHEMA_BASE_URL
          value: https://raw.githubusercontent.com/HumanCellAtlas/metadata-schema/4.6.1/json_schema/ontology_json
        - name: OLS_API_URL
          value: http://${INGEST_ONTOLOGY_SERVICE_SERVICE_HOST}:${INGEST_ONTOLOGY_SERVICE_SERVICE_PORT}/api
        - name: UPLOAD_API_KEY
          valueFrom:
            secretKeyRef:
              key: staging-api-key
              name: api-keys
        image: quay.io/humancellatlas/ingest-validator:master
        imagePullPolicy: Always
        name: ingest-validator
