apiVersion: v1
kind: Service
metadata:
  name: default-backend
  labels:
    app.kubernetes.io/name: default-backend
    app.kubernetes.io/part-of: ingress-nginx
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: default-backend
    app.kubernetes.io/part-of: ingress-nginx
  
    
