upload: upload.dev.data.humancellatlas.org
dss: dss.dev.data.humancellatlas.org
schema: schema.dev.data.humancellatlas.org
ingest: api.ingest.dev.data.humancellatlas.org
broker: ingest.dev.data.humancellatlas.org

# config values
gcpProjectWhitelist: "hca-dcp-production.iam.gserviceaccount.com,human-cell-atlas-travis-test.iam.gserviceaccount.com,broad-dsde-mint-dev.iam.gserviceaccount.com,broad-dsde-mint-test.iam.gserviceaccount.com,broad-dsde-mint-staging.iam.gserviceaccount.com"
svcAuthAudience: https://dev.data.humancellatlas.org/
usrAuthAudience: https://dev.data.humancellatlas.org/