upload: upload.data.humancellatlas.org
dss: dss.data.humancellatlas.org
schema: schema.humancellatlas.org
ingest: api.ingest.data.humancellatlas.org
broker: ingest.data.humancellatlas.org

# config values
gcpProjectWhitelist: "hca-dcp-pipelines-prod.iam.gserviceaccount.com,hca-dcp-production.iam.gserviceaccount.com"
svcAuthAudience: https://data.humancellatlas.org/
usrAuthAudience: https://dev.data.humancellatlas.org/

# ui
domainWhitelist: "api.ingest.data.humancellatlas.org,ingest.data.humancellatlas.org"
