apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    role: ontology-service
  name: ontology-service
  namespace: {{ .Values.environment }}-environment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ontology
  sessionAffinity: None
  type: LoadBalancer
